# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'
  pod 'Firebase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  # Pods for MyTestApp

end
