# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMD_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CMD_Practice
  pod 'SnapKit'
  pod 'Then'
  pod 'Moya'
end
