# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabBar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabBar
    pod 'Alamofire'
  pod 'lottie-ios'
  pod 'Moya'
end
